/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;

/**
 *
 * @author Mypc
 */
public class adminpanel extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
       static int invoicenum=1;
       String textareaset="";
       
        int productcode3;
    /**
     * Creates new form adminpanel
     */
    public adminpanel() {
        try
        {
            Class.forName("org.sqlite.JDBC");
             con=DriverManager.getConnection("jdbc:sqlite:test.sqlite");
        }
        catch(Exception e)
        {
            
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Record = new javax.swing.JButton();
        Billing = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LogOut = new javax.swing.JButton();
        productcode1 = new javax.swing.JTextField();
        productname1 = new javax.swing.JTextField();
        Unitprice1 = new javax.swing.JTextField();
        enteradd = new javax.swing.JButton();
        cancelaction = new javax.swing.JButton();
        okedit = new javax.swing.JButton();
        okdelete = new javax.swing.JButton();
        canceledit = new javax.swing.JButton();
        canceldelete = new javax.swing.JButton();
        okedit1 = new javax.swing.JButton();
        okdelete1 = new javax.swing.JButton();
        productcodelabel = new javax.swing.JLabel();
        productnamelabel = new javax.swing.JLabel();
        unitpricelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(70, 20, 120, 30);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(260, 20, 120, 30);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(450, 20, 130, 30);

        Record.setText("Record");
        Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordActionPerformed(evt);
            }
        });
        getContentPane().add(Record);
        Record.setBounds(640, 20, 130, 30);

        Billing.setText("Billing");
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });
        getContentPane().add(Billing);
        Billing.setBounds(840, 20, 130, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 200, 910, 300);

        LogOut.setText("LogOut");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut);
        LogOut.setBounds(400, 530, 150, 40);

        productcode1.setVisible(false);
        getContentPane().add(productcode1);
        productcode1.setBounds(70, 110, 210, 40);

        productname1.setVisible(false);
        getContentPane().add(productname1);
        productname1.setBounds(330, 110, 340, 40);

        Unitprice1.setVisible(false);
        getContentPane().add(Unitprice1);
        Unitprice1.setBounds(710, 110, 190, 40);

        enteradd.setVisible(false);
        enteradd.setText("OK");
        enteradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteraddActionPerformed(evt);
            }
        });
        getContentPane().add(enteradd);
        enteradd.setBounds(950, 110, 150, 40);

        cancelaction.setVisible(false);
        cancelaction.setText("Cancel");
        cancelaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelactionActionPerformed(evt);
            }
        });
        getContentPane().add(cancelaction);
        cancelaction.setBounds(1120, 110, 130, 40);

        okedit.setVisible(false);
        okedit.setText("OK");
        okedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeditActionPerformed(evt);
            }
        });
        getContentPane().add(okedit);
        okedit.setBounds(950, 110, 150, 40);

        okdelete.setVisible(false);
        okdelete.setText("OK");
        okdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(okdelete);
        okdelete.setBounds(950, 110, 150, 40);

        canceledit.setVisible(false);
        canceledit.setText("Cancel");
        canceledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceleditActionPerformed(evt);
            }
        });
        getContentPane().add(canceledit);
        canceledit.setBounds(1120, 110, 130, 40);

        canceldelete.setVisible(false);
        canceldelete.setText("Cancel");
        canceldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceldeleteActionPerformed(evt);
            }
        });
        getContentPane().add(canceldelete);
        canceldelete.setBounds(1120, 110, 130, 40);

        okedit1.setVisible(false);
        okedit1.setText("Ok");
        okedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okedit1ActionPerformed(evt);
            }
        });
        getContentPane().add(okedit1);
        okedit1.setBounds(950, 110, 150, 40);

        okdelete1.setVisible(false);
        okdelete1.setText("Ok");
        okdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okdelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(okdelete1);
        okdelete1.setBounds(950, 110, 150, 40);

        productcodelabel.setVisible(false);
        productcodelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productcodelabel.setText("Product Code");
        getContentPane().add(productcodelabel);
        productcodelabel.setBounds(110, 80, 160, 30);

        productnamelabel.setVisible(false);
        productnamelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productnamelabel.setText("Product Name");
        getContentPane().add(productnamelabel);
        productnamelabel.setBounds(380, 80, 250, 20);

        unitpricelabel.setVisible(false);
        unitpricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unitpricelabel.setText("Unit Price");
        getContentPane().add(unitpricelabel);
        unitpricelabel.setBounds(710, 80, 170, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
        InvoiceForm inv=new InvoiceForm();
        inv.setVisible(true);
        
    }//GEN-LAST:event_BillingActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        login loginf=new login();
        loginf.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
       cancelaction.setVisible(true);
        productname1.setVisible(true);
        productcodelabel.setVisible(false);
        productnamelabel.setVisible(true);
        unitpricelabel.setVisible(true);
        Unitprice1.setVisible(true);
        enteradd.setVisible(true);
        Edit.setEnabled(false);
        Delete.setEnabled(false);
        Record.setEnabled(false);
        Billing.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_AddActionPerformed

    private void cancelactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelactionActionPerformed
        // TODO add your handling code here:
         productname1.setVisible(false);
         cancelaction.setVisible(false);
        productcode1.setVisible(false);
        Unitprice1.setVisible(false);
        enteradd.setVisible(false);
        productcodelabel.setVisible(false);
        productnamelabel.setVisible(false);
        unitpricelabel.setVisible(false);
         Edit.setEnabled(true);
        Delete.setEnabled(true);
        Record.setEnabled(true);
        Billing.setEnabled(true);
    }//GEN-LAST:event_cancelactionActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        productcode1.setVisible(true);
        enteradd.setVisible(true);
        canceledit.setVisible(true);
         okedit.setVisible(true);
       productcodelabel.setVisible(true);
        productnamelabel.setVisible(false);
        unitpricelabel.setVisible(false);
         Add.setEnabled(false);
        Delete.setEnabled(false);
        Record.setEnabled(false);
        Billing.setEnabled(false);
       enteradd.setVisible(false);
        
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String productname3="";
        String unitprice1="";
         productcode1.setVisible(true);
         canceledit.setVisible(false);
         canceldelete.setVisible(true);
         okdelete.setVisible(true);
        okedit.setVisible(false);
         okedit1.setVisible(false);
         enteradd.setVisible(false);
         productcodelabel.setVisible(true);
        productnamelabel.setVisible(false);
        unitpricelabel.setVisible(false);
         Edit.setEnabled(false);
        Add.setEnabled(false);
        Record.setEnabled(false);
        Billing.setEnabled(false);
         
        
                 
        
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordActionPerformed
        // TODO add your handling code here:
        try
        {
             jTextArea1.setText("");
            PreparedStatement pst=con.prepareStatement("select * from products");
            ResultSet rs=pst.executeQuery();
           
            
            while(rs.next())
            {
                
                
                int productcode1=rs.getInt("productcode");
                String productcode2=Integer.toString(productcode1);
                String productname=rs.getString("productname");
                int unitprice=rs.getInt("unitprice");
                String unitprice1=Integer.toString(unitprice);
                textareaset=textareaset+productcode2+"                                                                          "+productname+"                                                                     "+unitprice1+"                                                                      "+"\n";
                
                
            }
            jTextArea1.setText(textareaset);
            textareaset="";
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_RecordActionPerformed

    private void enteraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteraddActionPerformed
        // TODO add your handling code here:
        String productnameadd=productname1.getText();
        String unitpriceadd=Unitprice1.getText();
        int unitpriceadd1=Integer.parseInt(unitpriceadd);
        try
        {
        stmt=con.createStatement();
        String sql= "INSERT INTO PRODUCTS(PRODUCTNAME,UNITPRICE)" +
                   "VALUES ('"+productnameadd+"','"+unitpriceadd1+"');";
        stmt.executeUpdate(sql);
     
        stmt.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_enteraddActionPerformed

    private void okeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeditActionPerformed
        // TODO add your handling code here:
        
        okedit.setVisible(false);
        try
        {   
            String productname3="";
            String unitprice1="";
            String productcode=productcode1.getText();
            productcode3=Integer.parseInt(productcode);
            stmt=con.createStatement();
        String sql= "select * from products where productcode='"+productcode3+"' ";
        
                 
        
        ResultSet rs=stmt.executeQuery(sql);
        while(rs.next())
        {
            productname3=rs.getString("productname");
          int unitprice=rs.getInt("unitprice");
           unitprice1=Integer.toString(unitprice);
        }
              
        stmt.close();
        productname1.setVisible(true);
        Unitprice1.setVisible(true);
        productname1.setText(productname3);
        Unitprice1.setText(unitprice1);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        okedit1.setVisible(true);
    }//GEN-LAST:event_okeditActionPerformed

    private void okedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okedit1ActionPerformed
        // TODO add your handling code here:
         String productname3=productname1.getText();
         System.out.print(productname3);
         String unitprice1=Unitprice1.getText();
         int unitprice2=Integer.parseInt(unitprice1);
        System.out.print(productcode3);
         try
         {
              String sql= "update products set productname=? , " +"unitprice=?"+ "where productcode=? ";
              PreparedStatement pst=con.prepareStatement(sql);
              pst.setString(1,productname3);
              pst.setInt(2,unitprice2);
              pst.setInt(3,productcode3);
              pst.executeUpdate();
              System.out.print(productname3);
        
         }
         catch(Exception e)
         {
             
         }
    }//GEN-LAST:event_okedit1ActionPerformed

    private void canceleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceleditActionPerformed
        // TODO add your handling code here:
        productname1.setVisible(false);
        cancelaction.setVisible(false);
        productcode1.setVisible(false);
         canceledit.setVisible(false);
         okedit.setVisible(false);
        productcode1.setVisible(false);
        Unitprice1.setVisible(false);
        enteradd.setVisible(false);
        okedit1.setVisible(false);
        productcodelabel.setVisible(false);
        productnamelabel.setVisible(false);
        unitpricelabel.setVisible(false);
        Add.setEnabled(true);
         Edit.setEnabled(true);
        Delete.setEnabled(true);
        Record.setEnabled(true);
        Billing.setEnabled(true);
    }//GEN-LAST:event_canceleditActionPerformed

    private void okdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okdeleteActionPerformed
        // TODO add your handling code here:
        okdelete1.setVisible(true);
        okdelete.setVisible(false);
        String productname3="";
        String unitprice1="";
        String productcode=productcode1.getText();
            productcode3=Integer.parseInt(productcode);
        String sql= "select * from products where productcode='"+productcode3+"' ";
        try
        {
            stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(sql);
        while(rs.next())
        {
            productname3=rs.getString("productname");
          int unitprice=rs.getInt("unitprice");
           unitprice1=Integer.toString(unitprice);
        }
          productname1.setVisible(true);
        Unitprice1.setVisible(true);
        productname1.setText(productname3);
        Unitprice1.setText(unitprice1);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_okdeleteActionPerformed

    private void okdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okdelete1ActionPerformed
        // TODO add your handling code here:
        
         try
         {
              String sql= "delete from products where productcode=? ";
              
              PreparedStatement pst=con.prepareStatement(sql);
               pst.setInt(1,productcode3);
               pst.executeUpdate();
        
         }
         catch(Exception e)
         {
             
         }
    }//GEN-LAST:event_okdelete1ActionPerformed

    private void canceldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceldeleteActionPerformed
        // TODO add your handling code here:
        productname1.setVisible(false);
        canceldelete.setVisible(false);
        productcode1.setVisible(false);
        okdelete.setVisible(false);
         okdelete1.setVisible(false);
        productcode1.setVisible(false);
        Unitprice1.setVisible(false);
        enteradd.setVisible(false);
        okedit1.setVisible(false);
        productcodelabel.setVisible(false);
        productnamelabel.setVisible(false);
        unitpricelabel.setVisible(false);
        Add.setEnabled(true);
         Edit.setEnabled(true);
        Delete.setEnabled(true);
        Record.setEnabled(true);
        Billing.setEnabled(true);
    }//GEN-LAST:event_canceldeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Billing;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Record;
    private javax.swing.JTextField Unitprice1;
    private javax.swing.JButton cancelaction;
    private javax.swing.JButton canceldelete;
    private javax.swing.JButton canceledit;
    private javax.swing.JButton enteradd;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okdelete;
    private javax.swing.JButton okdelete1;
    private javax.swing.JButton okedit;
    private javax.swing.JButton okedit1;
    private javax.swing.JTextField productcode1;
    private javax.swing.JLabel productcodelabel;
    private javax.swing.JTextField productname1;
    private javax.swing.JLabel productnamelabel;
    private javax.swing.JLabel unitpricelabel;
    // End of variables declaration//GEN-END:variables
}
