/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mypc
 */
public class InvoiceForm extends javax.swing.JFrame {
 Connection con;
 PreparedStatement stmt;
 int i=0,k=0,j;
 String i1="";
 int totalinvoice=0;
 int invoicenum;
 DefaultTableModel model = new DefaultTableModel(new String[] { "productcode", "product name", "unit price", "quantity", "Total"},0);
        
        
 
 public int initialize()
 {
     try
     {
    Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:test.sqlite");
           
            
     }
     catch(Exception e)
     {
         e.printStackTrace();
     }
      return i;
 }
 
    /**
     * Creates new form InvoiceForm
     */
   
    public InvoiceForm() {
        int j=initialize();
        i1=Integer.toString(j);
        initComponents();
       
    }
   public int getCount() {

        int count = 1;
        try {
            if ( !new File("E:\\myCount.txt").exists())
            {
                
                return 1;
            }
            else {
                BufferedReader br = new BufferedReader(new FileReader(new File("E:\\myCount.txt")));
                String s = br.readLine();
                count = Integer.parseInt(s);
                int s1=count;
                s1+=1;
                String s2=Integer.toString(s1);
                
                br.close();
              File myFoo = new File("E:\\myCount.txt");
                FileWriter fooWriter = new FileWriter(myFoo, false); 
                                                     
                     fooWriter.write(s2);
                     fooWriter.close();
                
              
            }                
        } catch(Exception e) {
            e.printStackTrace();
        }
        return count;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        invoiceno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        productcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        unitprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        subTotal = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        subtotal1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        New = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        productaddbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addaftertotal = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Invoice No :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 150, 30);

        invoiceno.setEditable(false);
        invoiceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicenoActionPerformed(evt);
            }
        });
        getContentPane().add(invoiceno);
        invoiceno.setBounds(150, 50, 240, 30);
        invoicenum=getCount();
        String invoicenum1=Integer.toString(invoicenum);
        invoiceno.setText(invoicenum1);

        jLabel2.setText("Customer Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 90, 20);
        getContentPane().add(customername);
        customername.setBounds(150, 110, 240, 30);

        jLabel3.setText("Date : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 60, 100, 20);
        getContentPane().add(Date);
        Date.setBounds(760, 60, 290, 30);

        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 120, 80, 14);
        getContentPane().add(Mobile);
        Mobile.setBounds(760, 110, 290, 30);

        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 100, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 240, 100);

        jLabel6.setText("Product Code");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 290, 100, 20);

        productcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productcodeActionPerformed(evt);
            }
        });
        getContentPane().add(productcode);
        productcode.setBounds(140, 310, 110, 30);

        jLabel7.setVisible(false);
        jLabel7.setText("Product Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 290, 90, 20);

        productname.setVisible(false);
        productname.setEditable(false);
        getContentPane().add(productname);
        productname.setBounds(280, 310, 230, 30);

        jLabel8.setVisible(false);
        jLabel8.setText("Unit Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 290, 90, 20);

        unitprice.setVisible(false);
        unitprice.setEditable(false);
        getContentPane().add(unitprice);
        unitprice.setBounds(540, 310, 100, 30);

        jLabel9.setVisible(false);
        jLabel9.setText("Quantity");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(700, 290, 80, 20);

        qty.setVisible(false);
        getContentPane().add(qty);
        qty.setBounds(680, 310, 90, 30);

        jLabel10.setVisible(false);
        jLabel10.setText("Total");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(840, 290, 60, 20);

        subTotal.setVisible(false);
        subTotal.setEditable(false);
        subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalActionPerformed(evt);
            }
        });
        getContentPane().add(subTotal);
        subTotal.setBounds(810, 310, 100, 30);

        Add.setVisible(false);
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(940, 310, 130, 30);

        jLabel11.setText("Subtotal");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(760, 510, 110, 30);

        subtotal1.setEditable(false);
        getContentPane().add(subtotal1);
        subtotal1.setBounds(840, 510, 230, 30);

        jLabel12.setText("Tax");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(770, 560, 60, 20);
        getContentPane().add(tax);
        tax.setBounds(840, 550, 230, 30);

        jLabel13.setText("Discount");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(760, 600, 50, 14);
        getContentPane().add(discount);
        discount.setBounds(840, 590, 230, 30);

        jLabel14.setText("   Total");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(760, 640, 60, 14);
        getContentPane().add(total);
        total.setBounds(840, 630, 230, 30);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(590, 690, 110, 30);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(720, 690, 120, 30);

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        getContentPane().add(New);
        New.setBounds(870, 690, 130, 30);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(1020, 690, 130, 30);

        productaddbutton.setText("Check");
        productaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productaddbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(productaddbutton);
        productaddbutton.setBounds(1090, 310, 130, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Unit Price", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 352, 930, 120);

        addaftertotal.setVisible(false);
        addaftertotal.setText("ADD");
        addaftertotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaftertotalActionPerformed(evt);
            }
        });
        getContentPane().add(addaftertotal);
        addaftertotal.setBounds(940, 310, 130, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mypc\\Downloads\\iIAj1C1.jpg")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, -16, 1350, 850);
        getContentPane().add(jOptionPane1);
        jOptionPane1.setBounds(220, 610, 262, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productcodeActionPerformed
        // TODO add your handling code here:
        String id=productcode.getText();
        int id1=Integer.parseInt(id);
        productname.setText(id);
        
        
    }//GEN-LAST:event_productcodeActionPerformed
    
    private void subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_subTotalActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
         productaddbutton.setVisible(false);
        productname.setVisible(false);
        unitprice.setVisible(false);
        qty.setVisible(false);
        subTotal.setVisible(false);
        String productcode1=productcode.getText();
        int productcode2=Integer.parseInt(productcode1);
        String productname1=productname.getText();
        String unitprice1=unitprice.getText();
        String quantity=qty.getText();
        int quantity1=Integer.parseInt(quantity);
        String total1=subTotal.getText();
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        
        jTable2.setModel(model);
        model.addRow(new Object[] { productcode1, productname1, unitprice1,
                quantity, total1 });
        productcode.setText("");
        productaddbutton.setVisible(true);
        Add.setVisible(false);
        addaftertotal.setVisible(false);
        String totalinvoice1=Integer.toString(totalinvoice);
        subtotal1.setText(totalinvoice1);
        try
        {
             String sql="INSERT INTO orderitems(invoiceid,productid,quantity) values(?,?,?)";
             PreparedStatement pst3=con.prepareStatement(sql);
             pst3.setInt(1,invoicenum);
             pst3.setInt(2,productcode2);
             pst3.setInt(3,quantity1);
             pst3.executeUpdate();
             
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_AddActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_printActionPerformed

    private void invoicenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicenoActionPerformed
        // TODO add your handling code here:
        
       
      
       
    }//GEN-LAST:event_invoicenoActionPerformed

    private void productaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productaddbuttonActionPerformed
        // TODO add your handling code here:
       
     try {
         
       
         PreparedStatement pst=con.prepareStatement("select * from products where productcode=?");
         
        String productcode1=productcode.getText();
        
        int productcode2=Integer.parseInt(productcode1);
        System.out.print(productcode2);
         pst.setInt(1,productcode2);
         ResultSet rs=pst.executeQuery();
         if(rs.next())
         {
            
             String productname1=rs.getString("productname");
         productname.setText(productname1);
         int productprice=rs.getInt("unitprice");
         String productprice1=Integer.toString(productprice);
         unitprice.setText(productprice1);
          productaddbutton.setVisible(false);
        productname.setVisible(true);
        unitprice.setVisible(true);
        qty.setVisible(true);
         jLabel7.setVisible(true);
       jLabel8.setVisible(true);
       jLabel9.setVisible(true);
        addaftertotal.setVisible(true);
                 }
         else
         {
             jOptionPane1.showMessageDialog(jLabel15, "the item does not exists");
         }
     } catch (Exception ex) {
        System.out.print(ex);
     }
        
        
    }//GEN-LAST:event_productaddbuttonActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
       
       this.setVisible(false);
       InvoiceForm inv1=new InvoiceForm();
       inv1.setVisible(true);
       
    }//GEN-LAST:event_NewActionPerformed

    private void addaftertotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaftertotalActionPerformed
        // TODO add your handling code here:
        String quantity=qty.getText();
        int quantity1=Integer.parseInt(quantity);
        String unitprice1=unitprice.getText();
        int unitprice2=Integer.parseInt(unitprice1);
        int total=quantity1*unitprice2;
        String total1=Integer.toString(total);
        subTotal.setVisible(true);
        subTotal.setText(total1);
        Add.setVisible(true);
        
      jLabel10.setVisible(true);
        
        
        
        totalinvoice=totalinvoice+total;
    }//GEN-LAST:event_addaftertotalActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
       
        String customername1=customername.getText();
        String sql="INSERT INTO customerpayment(invoiceid,customername,billamount) values(?,?,?)";
        try
        {
        stmt=con.prepareStatement(sql);
        stmt.setInt(1,invoicenum);
        
        stmt.setString(2,customername1);
        stmt.setInt(3,totalinvoice);
        
        
        
        stmt.executeUpdate();
        
        stmt.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        try
        {
        con.close();
        }
        catch(Exception e)
        {
          e.printStackTrace();  
        }
    }//GEN-LAST:event_saveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
         try
        {
             String sql="delete from orderitems where invoiceid=?";
             PreparedStatement pst3=con.prepareStatement(sql);
             pst3.setInt(1,invoicenum);
             
             pst3.executeUpdate();
             this.setVisible(false);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Mobile;
    private javax.swing.JButton New;
    private javax.swing.JButton addaftertotal;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField discount;
    public javax.swing.JTextField invoiceno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton print;
    private javax.swing.JButton productaddbutton;
    private javax.swing.JTextField productcode;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTextField subtotal1;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JTextField unitprice;
    // End of variables declaration//GEN-END:variables
}
