/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

/**
 *
 * @author Mypc
 */
public class login extends javax.swing.JFrame {
  Connection con;
  Statement stmt; 
    /**
     * Creates new form NewJFrame
     */
    public login() {
        try
        {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:test.db");
            stmt = con.createStatement();
      String sql = "CREATE TABLE IF NOT EXISTS CUSTOMER " +
                   "(USERNAME VARCHAR NOT NULL," +
                   " PASSWORD VARCHAR NOT NULL)"; 
      stmt.executeUpdate(sql);
	  PreparedStatement pst=con.prepareStatement("SELECT * from CUSTOMER where username=? and password=?");
           pst.setString(1,"dinesh");
           pst.setString(2,"dinesh1459");
           ResultSet rs=pst.executeQuery();
           if(!rs.next())
           {
               String sql1 = "INSERT INTO CUSTOMER (USERNAME,PASSWORD)" +
                   "VALUES ('dinesh','dinesh1459');"; 
      stmt.executeUpdate(sql1);
           }
           
       
      stmt.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        initComponents();
    }
  public void initialize()
  {
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        validate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ayush Billing");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 30, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 140, 240, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 220, 120, 20);
        getContentPane().add(username);
        username.setBounds(840, 140, 240, 40);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(540, 420, 160, 50);
        getContentPane().add(password);
        password.setBounds(840, 210, 240, 40);
        getContentPane().add(validate);
        validate.setBounds(430, 500, 460, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        try
        {
            String username1=username.getText();
            String password1=password.getText();
           
          
           System.out.println("Opened database successfully");
           
           System.out.print("created database");
          
          
          PreparedStatement pst=con.prepareStatement("SELECT * from CUSTOMER where username=? and password=?");
           pst.setString(1,username1);
           pst.setString(2,password1);
           ResultSet rs=pst.executeQuery();
           if(rs.next())
           {
               this.setVisible(false);
              adminpanel adm=new adminpanel();
              adm.setVisible(true);
           }
           else
           {
               validate.setText("Invalid username or password");
           }
          
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    private javax.swing.JLabel validate;
    // End of variables declaration//GEN-END:variables
}
